In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [3]:
df=pd.read_csv("machine_failure_dataset.csv")

In [4]:
x=df[['Power_Usage', 'Vibration', 'Humidity']]

In [5]:
y = df['Temperature']

In [6]:
model = LinearRegression()
model.fit(x, y)

LinearRegression()

In [7]:
p=model.predict(x)

In [8]:
mean_squared_error(y,p)

95.56457765346364

In [9]:
model.predict([[8.4617153,60.37630436,23.56418216]])

c:\Users\sanjay\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([69.41002337])

In [10]:
df.corr(numeric_only=True)

              Temperature  Vibration  Power_Usage  Humidity  Failure_Risk
Temperature      1.000000  -0.040400     0.022129 -0.013321      0.029938
Vibration       -0.040400   1.000000    -0.011199 -0.054698     -0.001727
Power_Usage      0.022129  -0.011199     1.000000  0.021586      0.020971
Humidity        -0.013321  -0.054698     0.021586  1.000000     -0.018007
Failure_Risk     0.029938  -0.001727     0.020971 -0.018007      1.000000

In [11]:
df2=pd.read_csv("factory_sensor_simulator_2040.csv")

In [12]:
df2.corr(numeric_only=True)

,Installation_Year,Operational_Hours,Temperature_C,Vibration_mms,Sound_dB,Oil_Level_pct,Coolant_Level_pct,Power_Consumption_kW,Last_Maintenance_Days_Ago,Maintenance_History_Count,Failure_History_Count,AI_Supervision,Error_Codes_Last_30_Days,Remaining_Useful_Life_days,Failure_Within_7_Days,Laser_Intensity,Hydraulic_Pressure_bar,Coolant_Flow_L_min,Heat_Index,AI_Override_Events
Installation_Year,1.000000,0.000625,0.000934,-0.000878,0.000196,-0.000762,-0.002217,0.000576,-0.000942,-0.000827,-0.000897,-0.000165,-0.000371,-0.000510,-0.001872,0.013024,0.002252,-0.000215,0.001208,0.000557
Operational_Hours,0.000625,1.000000,-0.000758,-0.001896,0.000883,0.002059,-0.001338,-0.000113,-0.002554,-0.000092,0.000598,-0.001895,-0.003748,-0.984784,0.396812,-0.006760,-0.006127,0.000614,-0.001520,-0.003557
Temperature_C,0.000934,-0.000758,1.000000,0.000925,0.000421,-0.002386,-0.001833,0.000984,-0.001257,0.000770,-0.001841,-0.002198,-0.001626,-0.024410,0.026189,-0.006778,-0.003049,0.005296,-0.000666,-0.000711
Vibration_mms,-0.000878,-0.001896,0.000925,1.000000,0.000214,-0.000237,0.001189,0.001631,-0.001191,-0.000285,0.001360,0.001839,-0.000279,-0.030622,0.037124,0.003357,-0.003877,-0.010611,-0.007354,0.000710
Sound_dB,0.000196,0.000883,0.000421,0.000214,1.000000,-0.000290,0.000729,-0.000273,0.000479,-0.000778,-0.000972,0.002622,0.000483,-0.000936,-0.001354,0.006160,0.000842,0.003056,-0.002612,0.001451
Oil_Level_pct,-0.000762,0.002059,-0.002386,-0.000237,-0.000290,1.000000,-0.001206,0.001369,0.000254,-0.001892,-0.002602,-0.000433,0.000619,-0.002023,-0.000885,0.005533,0.004219,0.000254,-0.004838,-0.000224
Coolant_Level_pct,-0.002217,-0.001338,-0.001833,0.001189,0.000729,-0.001206,1.000000,0.000582,-0.000149,-0.000908,-0.002201,0.001273,-0.000592,0.001492,-0.002152,0.008087,-0.007016,0.008710,-0.007038,0.001793
Power_Consumption_kW,0.000576,-0.000113,0.000984,0.001631,-0.000273,0.001369,0.000582,1.000000,0.003241,-0.000024,0.001435,0.001043,-0.000372,0.000015,0.000071,-0.010987,-0.006949,-0.001404,-0.007290,-0.000754
Last_Maintenance_Days_Ago,-0.000942,-0.002554,-0.001257,-0.001191,0.000479,0.000254,-0.000149,0.003241,1.000000,0.000413,-0.002777,0.000457,-0.003212,0.002463,0.000299,-0.010383,-0.004446,0.007440,-0.002418,-0.000447
Maintenance_History_Count,-0.000827,-0.000092,0.000770,-0.000285,-0.000778,-0.001892,-0.000908,-0.000024,0.000413,1.000000,0.000448,-0.001803,-0.001221,0.000080,-0.000308,-0.002491,0.005014,-0.007580,-0.003943,-0.000071
Failure_History_Count,-0.000897,0.000598,-0.001841,0.001360,-0.000972,-0.002602,-0.002201,0.001435,-0.002777,0.000448,1.000000,-0.000359,0.000830,-0.000751,0.002033,0.015380,-0.002427,0.006883,0.002694,-0.000294
AI_Supervision,-0.000165,-0.001895,-0.002198,0.001839,0.002622,-0.000433,0.001273,0.001043,0.000457,-0.001803,-0.000359,1.000000,-0.001029,0.002130,0.000357,0.001739,0.015306,-0.004264,-0.002256,0.762604
Error_Codes_Last_30_Days,-0.000371,-0.003748,-0.001626,-0.000279,0.000483,0.000619,-0.000592,-0.000372,-0.003212,-0.001221,0.000830,-0.001029,1.000000,0.003214,-0.000911,-0.004612,0.002040,0.001074,-0.005268,-0.001899
Remaining_Useful_Life_days,-0.000510,-0.984784,-0.024410,-0.030622,-0.000936,-0.002023,0.001492,0.000015,0.002463,0.000080,-0.000751,0.002130,0.003214,1.000000,-0.395519,0.007723,0.005929,0.000917,0.002738,0.003726
Failure_Within_7_Days,-0.001872,0.396812,0.026189,0.037124,-0.001354,-0.000885,-0.002152,0.000071,0.000299,-0.000308,0.002033,0.000357,-0.000911,-0.395519,1.000000,0.002307,-0.005669,-0.005955,-0.004637,-0.002043
Laser_Intensity,0.013024,-0.006760,-0.006778,0.003357,0.006160,0.005533,0.008087,-0.010987,-0.010383,-0.002491,0.015380,0.001739,-0.004612,0.007723,0.002307,1.000000,NaN,NaN,NaN,0.008460
Hydraulic_Pressure_bar,0.002252,-0.006127,-0.003049,-0.003877,0.000842,0.004219,-0.007016,-0.006949,-0.004446,0.005014,-0.002427,0.015306,0.002040,0.005929,-0.005669,NaN,1.000000,NaN,NaN,0.012293
Coolant_Flow_L_min,-0.000215,0.000614,0.005296,-0.010611,0.003056,0.000254,0.008710,-0.001404,0.007440,-0.007580,0.006883,-0.004264,0.001074,0.000917,-0.005955,NaN,NaN,1.000000,NaN,-0.007623
Heat_Index,0.001208,-0.001520,-0.000666,-0.007354,-0.002612,-0.004838,-0.007038,-0.007290,-0.002418,-0.003943,0.002694,-0.002256,-0.005268,0.002738,-0.004637,NaN,NaN,NaN,1.000000,0.001964
AI_Override_Events,0.000557,-0.003557,-0.000711,0.000710,0.001451,-0.000224,0.001793,-0.000754,-0.000447,-0.000071,-0.000294,0.762604,-0.001899,0.003726,-0.002043,0.008460,0.012293,-0.007623,0.001964,1.000000

In [13]:
df2=pd.read_csv("industrial_fault_detection_data_1000.csv")

In [14]:
df2.corr(numeric_only=True)

,Vibration (mm/s),Temperature (°C),Pressure (bar),RMS Vibration,Mean Temp,Fault Label
Vibration (mm/s),1.000000,0.029310,0.014518,NaN,NaN,-0.031799
Temperature (°C),0.029310,1.000000,0.027262,NaN,NaN,-0.007783
Pressure (bar),0.014518,0.027262,1.000000,NaN,NaN,0.008727
RMS Vibration,NaN,NaN,NaN,NaN,NaN,NaN
Mean Temp,NaN,NaN,NaN,NaN,NaN,NaN
Fault Label,-0.031799,-0.007783,0.008727,NaN,NaN,1.000000

In [15]:
import pickle
with open("temperature_model.pkl", "wb") as f:
    pickle.dump(model, f)