In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [2]:
df=pd.read_csv("art_restoration_dataset.csv")

In [3]:
df.head()

,image_name,blur_score,brightness,contrast,edge_count,damage_percent,restoration_cost
0,07_RESTORATION_BEFORE.png,1532.876678,136.902710,82.433736,4140,8.280,249.051943
1,alex-before.jpg,804.065380,87.157150,41.099469,3257,6.514,196.662135
2,angel.jpg,469.078146,147.353027,44.194559,2796,5.592,169.887306
3,ArchimedesConservation_05-before.png,701.245648,58.590363,34.799702,2803,5.606,169.604003
4,arena-before.jpg,89.401504,85.312286,18.232274,635,1.270,49.161763

In [4]:
def restoration_level(x):
    if x<=5:
        return "Easy"
    elif x<=10:
        return "Moderate"
    elif x<=20:
        return "Difficult"
    else:
        return "Impossible"
df['restoration_level'] = df['damage_percent'].apply(restoration_level)

In [5]:
def restoration_level(x):
    if x<=5:
        return 0
    elif x<=10:
        return 1
    elif x<=20:
        return 2
    else:
        return 3
df['restoration_level'] = df['damage_percent'].apply(restoration_level)

In [6]:
df

,image_name,blur_score,brightness,contrast,edge_count,damage_percent,restoration_cost,restoration_level
0,07_RESTORATION_BEFORE.png,1532.876678,136.902710,82.433736,4140,8.280,249.051943,1
1,alex-before.jpg,804.065380,87.157150,41.099469,3257,6.514,196.662135,1
2,angel.jpg,469.078146,147.353027,44.194559,2796,5.592,169.887306,1
3,ArchimedesConservation_05-before.png,701.245648,58.590363,34.799702,2803,5.606,169.604003,1
4,arena-before.jpg,89.401504,85.312286,18.232274,635,1.270,49.161763,0
...,...,...,...,...,...,...,...,...
111,uncle-before.jpg,1427.897922,146.200882,60.920171,10672,21.344,641.019840,3
112,unnamed-oil-before.png,126.861000,103.255554,38.578423,1229,2.458,81.560993,0
113,vi-before.jpg,3861.909664,84.064301,33.823509,12665,25.330,760.158872,3
114,wc-before.jpg,500.677426,91.939072,60.968589,4110,8.220,248.593313,1
115,woman_before.png,438.648845,73.925903,44.945864,5906,11.812,356.634543,2

In [7]:
x=df[['damage_percent','blur_score','edge_count','brightness']]
y=df['restoration_level']

In [8]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=42)

In [9]:
model=GaussianNB()
model.fit(xtrain,ytrain)

GaussianNB()

In [10]:
model.score(xtest,ytest)

1.0

In [25]:
df.corr(numeric_only=True)

,blur_score,brightness,contrast,edge_count,damage_percent,restoration_cost,restoration_level
blur_score,1.000000,-0.125671,0.179564,0.742455,0.742455,0.742047,0.650053
brightness,-0.125671,1.000000,0.287105,0.173724,0.173724,0.175574,0.194050
contrast,0.179564,0.287105,1.000000,0.271100,0.271100,0.267418,0.328845
edge_count,0.742455,0.173724,0.271100,1.000000,1.000000,0.999816,0.920134
damage_percent,0.742455,0.173724,0.271100,1.000000,1.000000,0.999816,0.920134
restoration_cost,0.742047,0.175574,0.267418,0.999816,0.999816,1.000000,0.918560
restoration_level,0.650053,0.194050,0.328845,0.920134,0.920134,0.918560,1.000000